name: Domination
version: '${project.version}'
main: com.rosa.domination.Domination
api-version: 1.19
commands:
  arena:
  bluewins:
permissions:
  domination.staff:
    default: op
  domination.arena:
    default: true
