name: Domination
version: '1.0-SNAPSHOTaaaaaaaa'
main: com.rosa.domination.Domination
api-version: 1.19
commands:
  bluewins:
permissions:
  domination.staff:
    default: op
  domination.arena:
    default: true
